ALTER TABLE scraper_runs
  ADD COLUMN IF NOT EXISTS peak_ram_mb     INTEGER,
  ADD COLUMN IF NOT EXISTS avg_ram_mb      INTEGER,
  ADD COLUMN IF NOT EXISTS phase_durations JSONB,
  ADD COLUMN IF NOT EXISTS cooldown_hits   INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS items_attempted INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS items_skipped   INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS items_failed    INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS concurrent_with TEXT[]  DEFAULT '{}';
